source 'https://github.com/CocoaPods/Specs.git' # 官方库
project 'Runner.xcodeproj'

platform :ios, '13.0'
use_frameworks!

workspace 'Runner.xcworkspace'


target 'Runner' do
 
 pod 'KeychainAccess', '~> 4.2'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end 
